### PR TITLE
Abstraction to a 2-step API

### PR DESCRIPTION
**Pull request by ethanknox-palmetto**
## Why? 
This takes us there - dimensional_dbt is now as simple as we wanted it to be. 

## what changes? 
- pass it the ref and sql for getting the unique id of each source.
- write your select, cherry-picking from each source as you go.
dimensional-dbt does the rest! 

## how does this impact me? 
real kimball dims and facts just became trivial from a technical implementation standpoint.

[LOOM](https://www.loom.com/share/fa1624b7c416442db3a5bc9b19a76f3d)

### CODE REVIEW

**Comment by jakeberesford-palmetto** [comment]
This is slick, but needs a lot more documentation. I'd probably add the following:

1. Comments, lots of them.
2. README - what is this? how do I use it? Link to a Loom demo
3. git actions to run the tests - I see you have tests, but no way to know if they are passing!

**Comment by ethanknox-palmetto** [comment]
per @jakeberesford-palmetto's feedback - 
1. major updates to comments and docs, readme. 
2. README has step-by-steps
3. CI is set up (won't run until it's merged tho)

**Review by jakeberesford-palmetto — APPROVED** [review]
Saw this working in group review, comments and readme are helpful - Approved!

**Comment by emekdahl-palmetto** [comment]
group PR review - approving so we can move along with the sprint

**Review by emekdahl-palmetto — APPROVED** [review]

**Pull request merged**
